# fly.toml app configuration file generated for deepface-workweek on 2025-01-10T16:22:49+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'deepface-workweek'
primary_region = 'jnb'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '5000'

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    path = "/health"
    protocol = "http"
    restart_limit = 0
    timeout = "5s"
  [http_service.concurrency]
    type = "requests"
    hard_limit = 250
    soft_limit = 200

[[services]]
  protocol = "tcp"
  internal_port = 5000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  
  [[services.tcp_checks]]
    interval = "15s"
    timeout = "5s"
    grace_period = "10s"
    port = 5000

[http_service.tls]
  alpn = ["h2", "http/1.1"]
  versions = ["TLSv1.2", "TLSv1.3"]

[[vm]]
  size = 'performance-2x'
  memory = '8gb'
  cpu_kind = 'performance'
  cpus = 2
  root_fs_size = "10gb"

[mounts]
  source = "deepface_data"
  destination = "/data"
