# fly.toml app configuration file generated for deepface-workweek on 2025-01-10T16:22:49+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'deepface-workweek'
primary_region = 'jnb'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '5000'

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[http_service.tls]
  alpn = ["h2", "http/1.1"]
  versions = ["TLSv1.2", "TLSv1.3"]

[[vm]]
  size = 'performance-2x'
  memory = '4gb'
  cpu_kind = 'performance'
  cpus = 2
